// react/src/views/Advanced/LongListOptimization/ListItem.tsx
import { memo } from "react";
import type { FC, ReactNode } from "react";
import "./ListItem.scss";
interface ListItemProps {
  children?: ReactNode;
  itemData: {
    id: number;
    name: string;
    count: number;
  };
}
const ListItem: FC<ListItemProps> = (props) => {
  return (
    <div className="list-item-container">
      <div className="list-item-id">id:{props.itemData.id}</div>
      <div className="list-item-name">name:{props.itemData.name}</div>
      <div className="list-item-count">count:{props.itemData.count}</div>
    </div>
  );
};
export default memo(ListItem);

// vue/src/views/Advanced/LongListOptimization/ListItem.vue
<template>
  <div class="list-item-container">
    <div class="list-item-id">id:{{ itemData.id }}</div>
    <div class="list-item-name">name:{{ itemData.name }}</div>
    <div class="list-item-count">count:{{ itemData.count }}</div>
  </div>
</template>

<script setup lang="ts" name="ListItem">
interface Props {
  itemData: { id: number; name: string; count: number };
}
defineProps<Props>();
</script>

<style lang="scss" scoped>
.list-item-container {
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 54px;
  padding: 0.5rem;
  background-color: cadetblue;
  box-sizing: border-box;
}
</style>
