// vue/src/views/Advanced/LongListOptimization/index.vue
<template>
  <div class="long-list-optimization-container">
    <div class="item-equal-height">
      <h1>等高</h1>
      <RecycleScroller
        class="scroll"
        :listData="list"
        :itemHeight="54"
        :itemGap="20"
      >
        <template #item="{ item }">
          <ListItem :itemData="item"></ListItem>
        </template>
      </RecycleScroller>
    </div>
    <div class="item-unequal-height">
      <h1>不等高</h1>
      <EstimatedVirtualList class="scroll" :items="UnequalList">
        <template #default="{ item }">
          <div class="list-item">{{ item.id }}-{{ item.content }}</div>
        </template>
      </EstimatedVirtualList>
    </div>
  </div>
</template>

<script setup lang="ts" name="LongListOptimization">
import ListItem from "./ListItem.vue";
import RecycleScroller from "./EqualHeight/RecycleScroller.vue";
import EstimatedVirtualList from "./UnequalHeight/EstimatedVirtualList.vue";
import { ref } from "vue";
const list = new Array(10000).fill(0).map((_, index) => {
  return { id: index, name: `item ${index}`, count: index };
});
const UnequalList = ref<any[]>([]);
fetch("/api/list")
  .then((res) => res.json())
  .then((res) => {
    UnequalList.value = res.data.list;
  });
</script>

<style lang="scss" scoped>
@use "@/assets/css/mixin.scss" as mixin;
.long-list-optimization-container {
  display: flex;
  height: 100%;
  h1 {
    text-align: center;
    margin-bottom: 20px;
  }
  .item-equal-height {
    @include mixin.flex();
    justify-content: flex-start;
    flex-direction: column;
    flex: 1;
    height: 100%;
    background-color: antiquewhite;
    .scroll {
      width: 500px;
      height: 600px;
      background-color: beige;
    }
  }
  .item-unequal-height {
    @include mixin.flex();
    justify-content: flex-start;
    flex-direction: column;
    flex: 1;
    height: 100%;
    background-color: aqua;
    .scroll {
      width: 500px;
      height: 600px;
      background-color: beige;
      .list-item{
        padding: 10px;
        border-bottom: 2px solid #ccc;
      }
    }
  }
}
</style>

// react/src/views/Advanced/LongListOptimization/index.tsx
import { memo, useEffect, useState } from "react";
import type { FC, ReactNode } from "react";
import type { ItemData } from "./UnequalHeight";
import "./index.scss";
import RecycleScroller from "./EqualHeight/RecycleScroller";
import UnequalHeight from "./UnequalHeight";
import ListItem from "./ListItem";
import "@/http/mock";
interface LongListOptimizationProps {
  children?: ReactNode;
}
const LongListOptimization: FC<LongListOptimizationProps> = () => {
  const [listData, setListData] = useState<ItemData[]>([]);
  const dataSource = new Array(100000).fill(0).map((_, index) => ({
    id: index,
    name: `Item ${index}`,
    count: index,
  }));
  useEffect(() => {
    fetch("/api/list")
      .then((res) => res.json())
      .then((res) => {
        setListData(res.data.list);
      });
  }, []);
  return (
    <div className="long-list-optimization-container">
      <div className="item-equal-height">
        <h1>等高</h1>
        <RecycleScroller
          className="scroll"
          dataSource={dataSource}
          itemHeight={54}
          prev={10}
          next={10}
          itemGap={10}
          renderItem={(item) => <ListItem itemData={item} />}
        />
      </div>
      <div className="item-unequal-height">
        <h1>不等高</h1>
        <UnequalHeight items={listData} className="scroll">
          {(item) => (
            <div>
              id:{item.id};{item.content}
            </div>
          )}
        </UnequalHeight>
      </div>
    </div>
  );
};
export default memo(LongListOptimization);
