// 1-Border-radius-Previewer/react/src/App.tsx
import { memo, useRef, useState } from "react";
import type { FC, ReactNode } from "react";
import { Slider } from "antd";
import "./App.css";
interface AppProps {
  children?: ReactNode;
}
const App: FC<AppProps> = () => {
  const boxRef = useRef<HTMLDivElement>(null);
  const initialStyle = {
    borderWidth: 10,
    width: 100,
    height: 100,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  };
  const [style, setStyle] = useState(initialStyle);
  async function handelCopy() {
    const styleText = boxRef.current?.style.cssText;
    await navigator.clipboard.writeText(styleText as string);
    alert("Copied to clipboard");
  }
  return (
    <div className="app">
      <div className="box" style={style} ref={boxRef}></div>
      <div className="sliders">
        <div className="border-width">
          <span>边框宽度</span>
          <Slider
            value={style.borderWidth}
            onChange={(value) => setStyle({ ...style, borderWidth: value })}
          ></Slider>
        </div>
        <div className="box-width">
          <span>盒子宽度</span>
          <Slider
            value={style.width}
            onChange={(value) => setStyle({ ...style, width: value })}
          ></Slider>
        </div>
        <div className="box-height">
          <span>盒子高度</span>
          <Slider
            value={style.height}
            onChange={(value) => setStyle({ ...style, height: value })}
          ></Slider>
        </div>
        <div className="box-radius">
          <span>盒子左上圆角</span>
          <Slider
            value={style.borderTopLeftRadius}
            onChange={(value) =>
              setStyle({ ...style, borderTopLeftRadius: value })
            }
          ></Slider>
        </div>
        <div className="box-radius">
          <span>盒子右上圆角</span>
          <Slider
            value={style.borderTopRightRadius}
            onChange={(value) =>
              setStyle({ ...style, borderTopRightRadius: value })
            }
          ></Slider>
        </div>
        <div className="box-radius">
          <span>盒子左下圆角</span>
          <Slider
            value={style.borderBottomLeftRadius}
            onChange={(value) =>
              setStyle({ ...style, borderBottomLeftRadius: value })
            }
          ></Slider>
        </div>
        <div className="box-radius">
          <span>盒子右下圆角</span>
          <Slider
            value={style.borderBottomRightRadius}
            onChange={(value) =>
              setStyle({ ...style, borderBottomRightRadius: value })
            }
          ></Slider>
        </div>
      </div>
      <div className="btns">
        <button onClick={() => setStyle(initialStyle)}>重置</button>
        <button onClick={handelCopy}>复制样式</button>
      </div>
    </div>
  );
};
export default memo(App);

// Border-radius-Previewer/vue/src/App.vue
<template>
  <div class="app-container">
    <div class="box" :style="style" ref="box"></div>
    <div class="slides">
      <div class="border-width">
        <span>边框宽度:{{ boxInfo.borderWidth }}px</span>
        <el-slider v-model="boxInfo.borderWidth" />
      </div>
      <div class="box-width">
        <span>盒子宽度:{{ boxInfo.boxWidth }}px</span>
        <el-slider v-model="boxInfo.boxWidth" :max="max" />
      </div>

      <div class="box-height">
        <span>盒子高度:{{ boxInfo.boxHeight }}px</span>
        <el-slider v-model="boxInfo.boxHeight" :max="max" />
      </div>
      <div class="box-radius">
        <span>盒子圆角左上:{{ boxInfo.borderRadiusTopLeft }}px</span>
        <el-slider v-model="boxInfo.borderRadiusTopLeft" />
      </div>
      <div class="box-radius">
        <span>盒子圆角右上:{{ boxInfo.borderRadiusTopRight }}px</span>
        <el-slider v-model="boxInfo.borderRadiusTopRight" />
      </div>
      <div class="box-radius">
        <span>盒子圆角左下:{{ boxInfo.borderRadiusBottomLeft }}px</span>
        <el-slider v-model="boxInfo.borderRadiusBottomLeft" />
      </div>
      <div class="box-radius">
        <span>盒子圆角右下:{{ boxInfo.borderRadiusBottomRight }}px</span>
        <el-slider v-model="boxInfo.borderRadiusBottomRight" />
      </div>
      <button @click="reset">重置</button>
      <button @click="copy">复制样式</button>
    </div>
  </div>
</template>

<script setup lang="ts" name="app">
import { ElMessage } from "element-plus";
import { computed, reactive, useTemplateRef } from "vue";

interface BoxInfo {
  [props: string]: any;
}
const max = 400;
const boxRef = useTemplateRef("box");
const originBoxInfo: BoxInfo = {
  borderWidth: 10,
  boxWidth: 100,
  boxHeight: 100,
  borderRadiusTopLeft: 10,
  borderRadiusTopRight: 10,
  borderRadiusBottomLeft: 10,
  borderRadiusBottomRight: 10,
};
const boxInfo = reactive(JSON.parse(JSON.stringify(originBoxInfo)));
const style = computed(() => {
  if (boxInfo.borderWidth > Math.min(boxInfo.boxWidth, boxInfo.boxHeight) / 2) {
    boxInfo.borderWidth = Math.min(boxInfo.boxWidth, boxInfo.boxHeight) / 2;
  }
  return {
    borderWidth: `${boxInfo.borderWidth}px`,
    width: `${boxInfo.boxWidth}px`,
    height: `${boxInfo.boxHeight}px`,
    borderRadius: `${boxInfo.borderRadiusTopLeft}px ${boxInfo.borderRadiusTopRight}px ${boxInfo.borderRadiusBottomRight}px ${boxInfo.borderRadiusBottomLeft}px`,
  };
});

function reset() {
  for (const item in originBoxInfo) {
    boxInfo[item] = originBoxInfo[item];
  }
}
async function copy() {
  const styleText = boxRef.value?.style.cssText;
  await navigator.clipboard.writeText(styleText as string);
  ElMessage.success("Copied");
}
</script>

<style lang="scss" scoped>
.app-container {
  width: 1000px;
  height: 1000px;
  margin: 0 auto;
  background-color: bisque;
  .box {
    box-sizing: border-box;
    margin: 0 auto;
    background-color: aquamarine;
    border-color: #000;
    border-style: solid;
  }
}
</style>
