// react/src/views/Advanced/index.tsx
import { memo } from "react";
import type { FC, ReactNode } from "react";
import { Outlet } from "react-router-dom";
import Description from "@/components/Description";
import type { DataType } from "@/components/Description";
import "./index.scss";
interface AdvancedProps {
  children?: ReactNode;
}
const Advanced: FC<AdvancedProps> = () => {
  const tableData: DataType[] = [
    {
      name: "LongListOptimization",
      description: "虚拟列表(等高/不等高)",
      key: "LongListOptimization",
    },
  ];
  return (
    <div className="advanced-container">
      <Description data={tableData} PositionData={{ bottom: 10, right: 10 }} />
      <Outlet />
    </div>
  );
};
export default memo(Advanced);

// vue/src/views/Advanced/index.vue
<template>
  <div class="advanced-container">
    <Description :table-data="tableData" :bottom="10" :right="10" />
    <router-view></router-view>
  </div>
</template>

<script setup lang="ts" name="Advanced">
import Description from "@/components/Description.vue";
const tableData = [
  {
    name: "Long List Optimization",
    des: "长列表优化(等高/不等高)",
    link: "",
  },
];
</script>

<style lang="scss" scoped>
.advanced-container {
  position: absolute;
  width: 100%;
  height: 100%;
  padding: 10px;
  box-sizing: border-box;
}
</style>
